export const chatContacts = [
  {
    id: "maya",
    name: "Maya Deshmukh",
    role: "Roommate match",
    status: "Online",
    location: "Pune",
    unreadCount: 2,
    lastMessage: "The flat near FC Road looks good. Should we shortlist it?",
    lastMessageTime: "2m",
    avatarColor: "from-indigo-400 to-cyan-300",
  }, // todo:id,name,unreadCount,lastMessage,lastMessageTime,
  {
    id: "aarav",
    name: "Aarav Mehta",
    role: "Housing lead",
    status: "Usually replies fast",
    location: "Bengaluru",
    unreadCount: 0,
    lastMessage: "I can visit the place tomorrow after class.",
    lastMessageTime: "28m",
    avatarColor: "from-violet-400 to-indigo-300",
  },
  {
    id: "sana",
    name: "Sana Khan",
    role: "Roommate match",
    status: "Away",
    location: "Mumbai",
    unreadCount: 0,
    lastMessage: "My budget is flexible if the commute is shorter.",
    lastMessageTime: "1h",
    avatarColor: "from-fuchsia-400 to-rose-300",
  },
  {
    id: "rohan",
    name: "Rohan Iyer",
    role: "Listing owner",
    status: "Offline",
    location: "Delhi",
    unreadCount: 0,
    lastMessage: "Sharing the deposit details here for reference.",
    lastMessageTime: "Yesterday",
    avatarColor: "from-amber-300 to-orange-400",
  },
];

export const chatMessages = {
  maya: [
    {
      id: "maya-1",
      sender: "other",
      text: "Hey, I checked the listing you sent. The area seems safe and close to metro.",
      time: "10:18 AM",
    },
    {
      id: "maya-2",
      sender: "me",
      text: "Nice. I liked that the room gets good sunlight and has a study table already.",
      time: "10:20 AM",
      status: "Seen",
    },
    {
      id: "maya-3",
      sender: "other",
      text: "Same. The flat near FC Road looks good. Should we shortlist it?",
      time: "10:21 AM",
    },
    {
      id: "maya-4",
      sender: "me",
      text: "Yes, let us keep it on top. I can message the owner and ask about visiting slots.",
      time: "10:23 AM",
      status: "Delivered",
    },
  ],
  aarav: [
    {
      id: "aarav-1",
      sender: "other",
      text: "The broker said the room is available from next week.",
      time: "9:42 AM",
    },
    {
      id: "aarav-2",
      sender: "me",
      text: "Good timing. Can you check if the rent includes maintenance?",
      time: "9:45 AM",
      status: "Seen",
    },
    {
      id: "aarav-3",
      sender: "other",
      text: "I can visit the place tomorrow after class.",
      time: "9:50 AM",
    },
  ],
  sana: [
    {
      id: "sana-1",
      sender: "other",
      text: "I usually cook twice a week and keep weekdays quiet after 11.",
      time: "Yesterday",
    },
    {
      id: "sana-2",
      sender: "me",
      text: "That works for me. My schedule is similar during exams.",
      time: "Yesterday",
      status: "Seen",
    },
    {
      id: "sana-3",
      sender: "other",
      text: "My budget is flexible if the commute is shorter.",
      time: "Yesterday",
    },
  ],
  rohan: [
    {
      id: "rohan-1",
      sender: "other",
      text: "The listing has two rooms available, both fully furnished.",
      time: "Mon",
    },
    {
      id: "rohan-2",
      sender: "me",
      text: "Can you share the deposit and lock-in details?",
      time: "Mon",
      status: "Seen",
    },
    {
      id: "rohan-3",
      sender: "other",
      text: "Sharing the deposit details here for reference.",
      time: "Mon",
    },
  ],
};
